__name__ = "kinesis-stream-consumer"
__version__ = "1.0.1"
__author__ = "Harshit"
__author_email__ = "harshittrivedi78@gmail.com"
__url__ = "https://github.com/harshittrivedi78/kinesis-stream-consumer"
